### ISSUE TITLE
JSONC parser is not used for filetype=jsonc

### ISSUE THREAD

**Issue by MunifTanjim** [nvim-treesitter/nvim-treesitter#1249]
**Describe the bug**

For `filetype=jsonc`, `json` parser is used, insead of `jsonc`. And that results in `ERROR` instead of `comment`.

![image](https://user-images.githubusercontent.com/8050659/115968073-b9085180-a557-11eb-914f-51b286c95d9b.png)

**To Reproduce**

- Config:

```viml
lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = {
    'html',
    'javascript', 'typescript', 'tsx', 
    'json', 'jsonc',
    'lua',
    'query',
    'regex',
    'rust',
    'toml',
    'yaml'
  },
  highlight = {
    enable = true,
  },
  indent = {
    enable = true
  },
  playground = {
    enable = true,
    disable = {},
    updatetime = 25,
    persist_queries = false,
    keybindings = {
      toggle_query_editor = 'o',
      toggle_hl_groups = 'i',
      toggle_injected_languages = 't',
      toggle_anonymous_nodes = 'a',
      toggle_language_display = 'I',
      focus_language = 'f',
      unfocus_language = 'F',
      update = 'R',
      goto_node = '<cr>',
      show_help = '?',
    },
  }
}
EOF
```

**Expected behavior**

`nvim-treesitter` should use the `jsonc` parser and detect comments correctly.

**Output of `:checkhealth nvim_treesitter`**

<details>

```
health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v14.15.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - lua            ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . 
  - json           ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ 
  - jsonc          ✓ ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

</details>

**Output of `nvim --version`**

<details>

```
…/nvim-treesitter  master [?1] via 🌙 took 7m37s
❯ nvim --version
NVIM v0.5.0-dev+1279-g11728988d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az36-884

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

</details>

**Additional context**

If `json` is not installed, then `jsonc` is used and it works correctly.

![image](https://user-images.githubusercontent.com/8050659/115968346-5b750480-a559-11eb-9131-ea688484c3a9.png)

**Comment by theHamsta** [comment]
Can you find out how the filetype json C is detected in your setup? I guess it's based on the modeline but probably the buffer's filetype was `json` for a short moment which caused the JSON parser to attach. Maybe you add a print statement here: https://github.com/theHamsta/nvim-treesitter/blob/aff9255ffa79643dae9e82497c0450976f61e77e/lua/nvim-treesitter/highlight.lua#L102 and when your ftdetect sets jsonc to determine what happens first. In any case the parser should be changed on changed filetype.

@WhyNotHugo

**Comment by MunifTanjim** [comment]
@theHamsta I'm actually trying `nvim-treesitter` for the first time. 

> Maybe you add a print statement here and when your ftdetect sets jsonc to determine what happens first. In any case the parser should be changed on changed filetype.

Can you please help me with this?

What should I add to that print? Just `print(lang)` or something else?

And how do I see that print output?

**Comment by theHamsta** [comment]
It is certainly a bug that we don't switch parsers on filetype change. Can you nevertheless tell us what behavior you want to have in your personal config. Do you want to admit comments in all json files or only those that have been explicitly marked as jsonc

**Comment by MunifTanjim** [comment]
> Do you want to admit comments in all json files or only those that have been explicitly marked as jsonc?

Ideally, comments should only be supported with `jsonc` type. I have this plugin installed: https://github.com/neoclide/jsonc.vim/blob/63ffa5199a0e64d5ce0515256407f32dfbd67fc3/ftdetect/jsonc.vim

I have all the common files that supports `jsonc` format. I use the *modeline*

**Comment by MunifTanjim** [comment]
> Do you want to admit comments in all json files or only those that have been explicitly marked as jsonc?

Ideally, comments should only be supported with `jsonc` type.

I use this plugin: https://github.com/neoclide/jsonc.vim/blob/63ffa5199a0e64d5ce0515256407f32dfbd67fc3/ftdetect/jsonc.vim
It sets the filetype to `jsonc` for all the common json files that support comments.

**Comment by MunifTanjim** [comment]
**Update**: `autocmd BufNewFile,BufRead` only works if it's added before initializing the plugin system. e.g.:

**These works:**

```viml
autocmd BufNewFile,BufRead tsconfig*.json setlocal filetype=jsonc
call plug#begin(data_dir . '/plugged')
  Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate' }
call plug#end()
```

or

```viml
call plug#begin(data_dir . '/plugged')
  Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate' }
  autocmd BufNewFile,BufRead tsconfig*.json setlocal filetype=jsonc
call plug#end()
```

**But this doesn't work:**

```viml
call plug#begin(data_dir . '/plugged')
  Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate' }
call plug#end()
autocmd BufNewFile,BufRead tsconfig*.json setlocal filetype=jsonc
```

---

> It is certainly a bug that we don't switch parsers on filetype change.

It would be nice if this was supported.

**Comment by WhyNotHugo** [comment]
> It is certainly a bug that we don't switch parsers on filetype change.

Is there a ticket to track progress on this or at least even discuss approaches to it? I've encountered the issue a few times (unrelated to this one though).

**Comment by vigoux** [comment]
Maybe we could add a jsonc filetype detection to the plugin just like #1289, that should fix the issue

**Comment by MunifTanjim** [comment]
@vigoux I already use this: https://github.com/neoclide/jsonc.vim , that doesn't solve the problem.

**Comment by theHamsta** [comment]
@vigoux the issue is not the filetype detect but when the detect happens too late. We don't react when the file type changes (e.g. we don't switch to jsonc when json is already attached). If ftdetect happens before the json parser is attached everything works fine

**Comment by stsewd** [comment]
Maybe `:h OptionSet` can help https://github.com/nvim-treesitter/nvim-treesitter/blob/f51e07e9facf1cd5d07a48bfe69acc106da142e4/lua/nvim-treesitter/configs.lua#L85-L85, haven't tested it.

**Comment by theHamsta** [comment]
@stsewd I guess this requires a complete disable/enable of the highlight module in order to work

**Comment by stsewd** [comment]
I have started playing with a solution for this, I found a bug while doing so https://github.com/neovim/neovim/pull/14995.

**Comment by stsewd** [comment]
This isn't fixed yet, it needs https://github.com/neovim/neovim/pull/14995, but making this an upstream issue instead.

**Comment by vatosarmat** [comment]
If reattaching is not currently supported is it possible to just always attach `jsonc`?
