### ISSUE TITLE
C# highlighting looks incomplete

### ISSUE THREAD

**Issue by Luxed** [nvim-treesitter/nvim-treesitter#1349]
The C# highlighting looks like it's missing some important parts.
In the following screenshots, you can see all of the following issues:

1. The method calls are never highlighted, only the method definitions are.
2. String's _quotes_ are highlighted with the string color, but not [interpolated strings](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated) where only the inside of the quotes is properly highlighted.
3. [Verbatim strings](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/verbatim) are not working at all.
4. Types are sometimes highlighted, sometimes not. In this case, Task and Console are good examples. Task especially gets highlighted in the method signature, but not in the method body, making the highlighting inconsistent.

![image](https://user-images.githubusercontent.com/10234894/120137551-985c9880-c1a2-11eb-84d0-d8569169aa5f.png)

Where it happens exactly:

1. lines 15 (`YesPrint()`), line 17 (`WhenAll()`, `ToArray()`), line 22 (`Delay()`), line 28 (`Delay()`), line 29 (`WriteLine`).
2. line 23 and line 29: `$""` should be `TSString` (green in my case).
3. line 13-14: `@""` and everything that is inside it should be highlighted with `TSString`.
4. lines 17, 22, 29: `Task` should be highlighted. line 29: `Console` should be highlighted. `TSType` should be sufficient.

I have no idea if all of these are even possible, I'd say the fourth issue is less important.
I would love to use a semantic highlighter for this language but the only one I know of is the official Omnisharp extension, which wouldn't work with the plugins I use. I also could not find any work done on supporting semantic highlighting directly in Neovim since it is now a part of the LSP spec (or am I wrong on that?).

**Comment by theHamsta** [comment]
The C# parser is very incomplete. It can't parser most documents properly. Semantic tokens for C# is in preview https://github.com/OmniSharp/omnisharp-vscode#semantic-highlighting

**Comment by theHamsta** [comment]
Also adding namespaces are not highlighted as such to the list

**Comment by theHamsta** [comment]
@svermeulen

**Comment by FTenner** [comment]
Highlighting used to be more complete until sometime before two weeks ago, I lost it when updating to latest neovim nightly.

**Comment by theHamsta** [comment]
Maybe there are some new queries missing? Has someone the time to look over the queries and fix them? I personally don't use C#.

**Comment by theHamsta** [comment]
Does #1351 improve the situation?

**Comment by Luxed** [comment]
> Does #1351 improve the situation?

You're too fast :stuck_out_tongue_closed_eyes:, I'll try it as soon as I can.

**Comment by Luxed** [comment]
@theHamsta Here's the result with your changes:
![image](https://user-images.githubusercontent.com/10234894/120249300-69006700-c248-11eb-9676-14d8f13d2fd7.png)

I believe `@for` should only be seen as a regular variable so this is working perfectly. It is only used in rare cases when you want to name a variable with a reserved name.
Everything I have asked for seems to be fixed, although I would need to work on a bigger, more realistic project to know if everything is working as intended. I will get back to you once I have the occasion to do that (not before tomorrow unfortunately).

**Comment by Luxed** [comment]
I found a few more issues with C# while looking through a 2000 line file.
I will be doing a Pull Request tomorrow to fix most of what I have found. I really wanted to do it myself for once :p

**Comment by theHamsta** [comment]
@Luxed will we also get folding and locals? :smiley:

**Comment by Luxed** [comment]
> @Luxed will we also get folding and locals? smiley

Hmmmmmmm, I was gonna do the PR right now, but I'll look into the folding for sure since I use folds by default.
As for locals, I don't even know what they are. Care to explain? (or just give a link to the specification or something)

**Comment by theHamsta** [comment]
Locals are some local semantic structure of the document. It basically answers the question "what is a definition?" "What is the scope of definition?" in the current language. And of course also when some definition is reference in code.

**Comment by theHamsta** [comment]
Really nice that you're helping to support your languages! I'm right now a bit busy and this helps a lot to keep the project going!

**Comment by Luxed** [comment]
> With those three lines you should have basic smart_rename in https://github.com/nvim-treesitter/nvim-treesitter-refactor/ and goto_definition

Ah, I see!
I'll look into that when I can, but for now, the other improvements are more important, so I'll just make a PR for that and I'll make a PR for the locals later.

> Really nice that you're helping to support your languages! I'm right now a bit busy and this helps a lot to keep the project going!

My pleasure!

**Comment by stsewd** [comment]
Was this solved by https://github.com/nvim-treesitter/nvim-treesitter/pull/1356? Or is there anything else we can improve?

**Comment by Luxed** [comment]
> Was this solved by #1356? Or is there anything else we can improve?

C# is still missing locals and indents.
I have also found some more issues since I finally started using it on a daily basis.
I'd like to keep this opened until what's left is fixed, would that be an issue?

**Comment by theHamsta** [comment]
Of course not. Leave it open until you think it is not an issue anymore
